name: DebugBuild

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"
  workflow_dispatch : 
    branches: "master"


env:
  SOLUTION_FILE_PATH: 2023_10days_remaster.sln
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        run: msbuild /m ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}} /p:BuildInParallel=true
